# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.54.3-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.paginated_rbac_role_list import PaginatedRbacRoleList

class TestPaginatedRbacRoleList(unittest.TestCase):
    """PaginatedRbacRoleList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedRbacRoleList:
        """Test PaginatedRbacRoleList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedRbacRoleList`
        """
        model = PaginatedRbacRoleList()
        if include_optional:
            return PaginatedRbacRoleList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    iblai.models.rbac_role.RbacRole(
                        id = 56, 
                        name = '', 
                        platform = null, 
                        platform_key = '', 
                        actions = [
                            ''
                            ], )
                    ]
            )
        else:
            return PaginatedRbacRoleList(
                count = 123,
                results = [
                    iblai.models.rbac_role.RbacRole(
                        id = 56, 
                        name = '', 
                        platform = null, 
                        platform_key = '', 
                        actions = [
                            ''
                            ], )
                    ],
        )
        """

    def testPaginatedRbacRoleList(self):
        """Test PaginatedRbacRoleList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
