# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 2.3.38-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.api.career_api import CareerApi


class TestCareerApi(unittest.TestCase):
    """CareerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CareerApi()

    def tearDown(self) -> None:
        pass

    def test_career_resume_orgs_users_create(self) -> None:
        """Test case for career_resume_orgs_users_create

        """
        pass

    def test_career_resume_orgs_users_retrieve(self) -> None:
        """Test case for career_resume_orgs_users_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
