# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 2.3.38-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.free_usage_count import FreeUsageCount

class TestFreeUsageCount(unittest.TestCase):
    """FreeUsageCount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FreeUsageCount:
        """Test FreeUsageCount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FreeUsageCount`
        """
        model = FreeUsageCount()
        if include_optional:
            return FreeUsageCount(
                count = 56
            )
        else:
            return FreeUsageCount(
                count = 56,
        )
        """

    def testFreeUsageCount(self):
        """Test FreeUsageCount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
