# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.89.4-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.invoice_report_response import InvoiceReportResponse

class TestInvoiceReportResponse(unittest.TestCase):
    """InvoiceReportResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceReportResponse:
        """Test InvoiceReportResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceReportResponse`
        """
        model = InvoiceReportResponse()
        if include_optional:
            return InvoiceReportResponse(
                entity = iblai.models.entity.Entity(
                    type = 'user', 
                    username = '', 
                    platform_key = '', 
                    platform_name = '', 
                    display_name = '', ),
                billing_period = iblai.models.billing_period.BillingPeriod(
                    start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    days = 56, ),
                summary = iblai.models.summary.Summary(
                    total_cost = '-8072', 
                    total_sessions = 56, 
                    active_users = 56, 
                    cost_per_session = '-8072', ),
                breakdown = iblai.models.breakdown.Breakdown(
                    by_provider = [
                        iblai.models.provider_breakdown.ProviderBreakdown(
                            provider = '', 
                            cost = '-8072', 
                            percentage = '-8072', )
                        ], 
                    by_mentor = [
                        iblai.models.mentor_breakdown.MentorBreakdown(
                            mentor = '', 
                            cost = '-8072', 
                            sessions = 56, 
                            mentor_name = '', )
                        ], 
                    by_action = [
                        iblai.models.action_breakdown.ActionBreakdown(
                            action = '', 
                            cost = '-8072', 
                            sessions = 56, 
                            trace_count = 56, 
                            unique_users = 56, )
                        ], )
            )
        else:
            return InvoiceReportResponse(
                entity = iblai.models.entity.Entity(
                    type = 'user', 
                    username = '', 
                    platform_key = '', 
                    platform_name = '', 
                    display_name = '', ),
                billing_period = iblai.models.billing_period.BillingPeriod(
                    start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    days = 56, ),
                summary = iblai.models.summary.Summary(
                    total_cost = '-8072', 
                    total_sessions = 56, 
                    active_users = 56, 
                    cost_per_session = '-8072', ),
        )
        """

    def testInvoiceReportResponse(self):
        """Test InvoiceReportResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
