# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.89.4-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.time_spent_detail import TimeSpentDetail

class TestTimeSpentDetail(unittest.TestCase):
    """TimeSpentDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimeSpentDetail:
        """Test TimeSpentDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimeSpentDetail`
        """
        model = TimeSpentDetail()
        if include_optional:
            return TimeSpentDetail(
                courses = [
                    iblai.models.time_spent_course.TimeSpentCourse(
                        course_id = '', 
                        course_name = '', 
                        platform = '', 
                        time_spent = '', 
                        time_spent_secs = 56, )
                    ],
                total_time_spent = '',
                total_time_spent_secs = 56,
                overtime = [
                    iblai.models.overtime_data_point.OvertimeDataPoint(
                        date = '', 
                        value = 56, )
                    ]
            )
        else:
            return TimeSpentDetail(
                courses = [
                    iblai.models.time_spent_course.TimeSpentCourse(
                        course_id = '', 
                        course_name = '', 
                        platform = '', 
                        time_spent = '', 
                        time_spent_secs = 56, )
                    ],
                total_time_spent = '',
                total_time_spent_secs = 56,
        )
        """

    def testTimeSpentDetail(self):
        """Test TimeSpentDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
