# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 2.3.36-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.perlearner_engagement_videos_watched_per_course import PerlearnerEngagementVideosWatchedPerCourse

class TestPerlearnerEngagementVideosWatchedPerCourse(unittest.TestCase):
    """PerlearnerEngagementVideosWatchedPerCourse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PerlearnerEngagementVideosWatchedPerCourse:
        """Test PerlearnerEngagementVideosWatchedPerCourse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PerlearnerEngagementVideosWatchedPerCourse`
        """
        model = PerlearnerEngagementVideosWatchedPerCourse()
        if include_optional:
            return PerlearnerEngagementVideosWatchedPerCourse(
                data = [
                    iblai.models.perlearner_engagement_videos_data.PerlearnerEngagementVideosData(
                        course_id = '', 
                        name = '', 
                        total_videos = 56, 
                        watched = 56, 
                        total_time_watch = 56, 
                        average_class_watch = 1.337, 
                        class_time_average = 1.337, )
                    ]
            )
        else:
            return PerlearnerEngagementVideosWatchedPerCourse(
                data = [
                    iblai.models.perlearner_engagement_videos_data.PerlearnerEngagementVideosData(
                        course_id = '', 
                        name = '', 
                        total_videos = 56, 
                        watched = 56, 
                        total_time_watch = 56, 
                        average_class_watch = 1.337, 
                        class_time_average = 1.337, )
                    ],
        )
        """

    def testPerlearnerEngagementVideosWatchedPerCourse(self):
        """Test PerlearnerEngagementVideosWatchedPerCourse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
