# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 2.3.38-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.course_grading_detail import CourseGradingDetail

class TestCourseGradingDetail(unittest.TestCase):
    """CourseGradingDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CourseGradingDetail:
        """Test CourseGradingDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CourseGradingDetail`
        """
        model = CourseGradingDetail()
        if include_optional:
            return CourseGradingDetail(
                data = [
                    iblai.models.course_grading_detail_data.CourseGradingDetailData(
                        display_name = '', 
                        id = '', 
                        subsections = [
                            iblai.models.course_grade_detail_sub_section.CourseGradeDetailSubSection(
                                display_name = '', 
                                id = '', 
                                attempts = '', 
                                average = '', 
                                problems = [
                                    iblai.models.course_grade_detail_block.CourseGradeDetailBlock(
                                        display_name = '', 
                                        id = '', 
                                        attempts = '', 
                                        average = '', )
                                    ], )
                            ], )
                    ]
            )
        else:
            return CourseGradingDetail(
        )
        """

    def testCourseGradingDetail(self):
        """Test CourseGradingDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
