# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.89.4-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.entity_type_enum import EntityTypeEnum

class TestEntityTypeEnum(unittest.TestCase):
    """EntityTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityTypeEnum(self):
        """Test EntityTypeEnum"""
        # inst = EntityTypeEnum()

if __name__ == '__main__':
    unittest.main()
