# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.202.1-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.paginated_google_agent_detail_list import PaginatedGoogleAgentDetailList

class TestPaginatedGoogleAgentDetailList(unittest.TestCase):
    """PaginatedGoogleAgentDetailList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedGoogleAgentDetailList:
        """Test PaginatedGoogleAgentDetailList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedGoogleAgentDetailList`
        """
        model = PaginatedGoogleAgentDetailList()
        if include_optional:
            return PaginatedGoogleAgentDetailList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    iblai.models.google_agent_detail.GoogleAgentDetail(
                        id = 56, 
                        sub_agents = '', 
                        platform = '', 
                        unique_id = '', 
                        model = '', 
                        name = '', 
                        description = '', 
                        instruction = '', 
                        output_key = '', 
                        inserted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = 56, )
                    ]
            )
        else:
            return PaginatedGoogleAgentDetailList(
                count = 123,
                results = [
                    iblai.models.google_agent_detail.GoogleAgentDetail(
                        id = 56, 
                        sub_agents = '', 
                        platform = '', 
                        unique_id = '', 
                        model = '', 
                        name = '', 
                        description = '', 
                        instruction = '', 
                        output_key = '', 
                        inserted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = 56, )
                    ],
        )
        """

    def testPaginatedGoogleAgentDetailList(self):
        """Test PaginatedGoogleAgentDetailList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
