# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.204.0-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.item_paywall_config_create import ItemPaywallConfigCreate

class TestItemPaywallConfigCreate(unittest.TestCase):
    """ItemPaywallConfigCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemPaywallConfigCreate:
        """Test ItemPaywallConfigCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemPaywallConfigCreate`
        """
        model = ItemPaywallConfigCreate()
        if include_optional:
            return ItemPaywallConfigCreate(
                is_enabled = True,
                description = '',
                allow_free_tier = True,
                trial_period_days = 0,
                grandfathering_strategy = 'free_forever'
            )
        else:
            return ItemPaywallConfigCreate(
        )
        """

    def testItemPaywallConfigCreate(self):
        """Test ItemPaywallConfigCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
