# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 2.4.1-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.pinned_message_request import PinnedMessageRequest

class TestPinnedMessageRequest(unittest.TestCase):
    """PinnedMessageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PinnedMessageRequest:
        """Test PinnedMessageRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PinnedMessageRequest`
        """
        model = PinnedMessageRequest()
        if include_optional:
            return PinnedMessageRequest(
                session_id = ''
            )
        else:
            return PinnedMessageRequest(
                session_id = '',
        )
        """

    def testPinnedMessageRequest(self):
        """Test PinnedMessageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
