# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.54.3-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.role import Role

class TestRole(unittest.TestCase):
    """Role unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Role:
        """Test Role
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Role`
        """
        model = Role()
        if include_optional:
            return Role(
                id = 56,
                name = '',
                slug = '',
                platform_key = '',
                skills = [
                    iblai.models.skill.Skill(
                        id = 56, 
                        name = '', 
                        platform_key = '', 
                        slug = 'z', 
                        data = null, )
                    ],
                data = None
            )
        else:
            return Role(
                id = 56,
                name = '',
                slug = '',
                skills = [
                    iblai.models.skill.Skill(
                        id = 56, 
                        name = '', 
                        platform_key = '', 
                        slug = 'z', 
                        data = null, )
                    ],
                data = None,
        )
        """

    def testRole(self):
        """Test Role"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
