# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.54.3-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.course_license_detail import CourseLicenseDetail

class TestCourseLicenseDetail(unittest.TestCase):
    """CourseLicenseDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CourseLicenseDetail:
        """Test CourseLicenseDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CourseLicenseDetail`
        """
        model = CourseLicenseDetail()
        if include_optional:
            return CourseLicenseDetail(
                id = 56,
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                started = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expired = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                count = 56,
                active = True,
                metadata = {
                    'key' : null
                    },
                source = '',
                external_id = '',
                platform_key = '',
                course_id = '',
                usage_count = 56
            )
        else:
            return CourseLicenseDetail(
                id = 56,
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                started = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expired = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                count = 56,
                active = True,
                metadata = {
                    'key' : null
                    },
                source = '',
                external_id = '',
                platform_key = '',
                course_id = '',
        )
        """

    def testCourseLicenseDetail(self):
        """Test CourseLicenseDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
