# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.54.3-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.mentor_memory_settings_request import MentorMemorySettingsRequest

class TestMentorMemorySettingsRequest(unittest.TestCase):
    """MentorMemorySettingsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MentorMemorySettingsRequest:
        """Test MentorMemorySettingsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MentorMemorySettingsRequest`
        """
        model = MentorMemorySettingsRequest()
        if include_optional:
            return MentorMemorySettingsRequest(
                item_type = '',
                item_identifier = '',
                learner_advance_correct_rate = 1.337,
                learner_advance_question_count = 56
            )
        else:
            return MentorMemorySettingsRequest(
        )
        """

    def testMentorMemorySettingsRequest(self):
        """Test MentorMemorySettingsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
