# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.54.3-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.google_pay_account_response_status_enum import GooglePayAccountResponseStatusEnum

class TestGooglePayAccountResponseStatusEnum(unittest.TestCase):
    """GooglePayAccountResponseStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGooglePayAccountResponseStatusEnum(self):
        """Test GooglePayAccountResponseStatusEnum"""
        # inst = GooglePayAccountResponseStatusEnum()

if __name__ == '__main__':
    unittest.main()
