# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 2.3.36-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.mentor_from_template_request import MentorFromTemplateRequest

class TestMentorFromTemplateRequest(unittest.TestCase):
    """MentorFromTemplateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MentorFromTemplateRequest:
        """Test MentorFromTemplateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MentorFromTemplateRequest`
        """
        model = MentorFromTemplateRequest()
        if include_optional:
            return MentorFromTemplateRequest(
                template_name = '',
                new_mentor_name = ''
            )
        else:
            return MentorFromTemplateRequest(
                template_name = '',
                new_mentor_name = '',
        )
        """

    def testMentorFromTemplateRequest(self):
        """Test MentorFromTemplateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
