# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.204.0-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.item_price_create import ItemPriceCreate

class TestItemPriceCreate(unittest.TestCase):
    """ItemPriceCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemPriceCreate:
        """Test ItemPriceCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemPriceCreate`
        """
        model = ItemPriceCreate()
        if include_optional:
            return ItemPriceCreate(
                name = '',
                description = '',
                amount = '-80728880',
                currency = '',
                interval = 'month',
                is_active = True,
                features = None,
                sort_order = 56
            )
        else:
            return ItemPriceCreate(
                name = '',
                amount = '-80728880',
        )
        """

    def testItemPriceCreate(self):
        """Test ItemPriceCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
