# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.54.3-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.course_invitation_redemption import CourseInvitationRedemption

class TestCourseInvitationRedemption(unittest.TestCase):
    """CourseInvitationRedemption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CourseInvitationRedemption:
        """Test CourseInvitationRedemption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CourseInvitationRedemption`
        """
        model = CourseInvitationRedemption()
        if include_optional:
            return CourseInvitationRedemption(
                course_id = '',
                source = '',
                email = '',
                username = '',
                metadata = {
                    'key' : null
                    }
            )
        else:
            return CourseInvitationRedemption(
                course_id = '',
                source = '',
        )
        """

    def testCourseInvitationRedemption(self):
        """Test CourseInvitationRedemption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
