# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.204.0-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.item_access_check_response import ItemAccessCheckResponse

class TestItemAccessCheckResponse(unittest.TestCase):
    """ItemAccessCheckResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemAccessCheckResponse:
        """Test ItemAccessCheckResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemAccessCheckResponse`
        """
        model = ItemAccessCheckResponse()
        if include_optional:
            return ItemAccessCheckResponse(
                has_access = True,
                item_type = 'mentor',
                item_id = '',
                reason = '',
                requires_payment = True,
                pricing_available = True,
                pricing = None,
                subscription = iblai.models.item_subscription.ItemSubscription(
                    unique_id = '', 
                    user_id = 56, 
                    username = '', 
                    email = '', 
                    item_type = null, 
                    item_id = '', 
                    item_name = '', 
                    status = null, 
                    price = null, 
                    current_period_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    current_period_end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    trial_end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    cancel_at_period_end = True, 
                    canceled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    is_grandfathered = True, 
                    grandfathered_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    billing_portal_url = '', 
                    metadata = null, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return ItemAccessCheckResponse(
                has_access = True,
                item_type = 'mentor',
                item_id = '',
                reason = '',
                requires_payment = True,
                pricing_available = True,
        )
        """

    def testItemAccessCheckResponse(self):
        """Test ItemAccessCheckResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
