# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.204.2-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.user_group_policy import UserGroupPolicy

class TestUserGroupPolicy(unittest.TestCase):
    """UserGroupPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserGroupPolicy:
        """Test UserGroupPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserGroupPolicy`
        """
        model = UserGroupPolicy()
        if include_optional:
            return UserGroupPolicy(
                id = 56,
                name = '',
                platform_key = '',
                usergroup_id = 56,
                role = '',
                resources = None,
                users = [
                    iblai.models.rbac_user.RbacUser(
                        id = 56, 
                        username = '', 
                        email = '', )
                    ],
                groups = [
                    iblai.models.rbac_policy_group.RbacPolicyGroup(
                        id = 56, 
                        name = '', 
                        unique_id = '', 
                        description = '', )
                    ],
                groups_to_add = [
                    56
                    ],
                groups_to_remove = [
                    56
                    ],
                users_to_add = [
                    56
                    ],
                users_to_remove = [
                    56
                    ]
            )
        else:
            return UserGroupPolicy(
                id = 56,
                name = '',
                platform_key = '',
                usergroup_id = 56,
                role = '',
                resources = None,
                users = [
                    iblai.models.rbac_user.RbacUser(
                        id = 56, 
                        username = '', 
                        email = '', )
                    ],
                groups = [
                    iblai.models.rbac_policy_group.RbacPolicyGroup(
                        id = 56, 
                        name = '', 
                        unique_id = '', 
                        description = '', )
                    ],
        )
        """

    def testUserGroupPolicy(self):
        """Test UserGroupPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
