# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 2.3.38-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.llm_response import LLMResponse

class TestLLMResponse(unittest.TestCase):
    """LLMResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LLMResponse:
        """Test LLMResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LLMResponse`
        """
        model = LLMResponse()
        if include_optional:
            return LLMResponse(
                id = 56,
                name = '',
                description = '',
                metadata = None,
                resource_ids = None,
                tags = None,
                overview = '',
                use_cases = '',
                documentation = '',
                sdk_samples = '',
                chat_models = None,
                logo = ''
            )
        else:
            return LLMResponse(
                id = 56,
                name = '',
        )
        """

    def testLLMResponse(self):
        """Test LLMResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
