# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.54.3-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.mentor_scenario import MentorScenario

class TestMentorScenario(unittest.TestCase):
    """MentorScenario unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MentorScenario:
        """Test MentorScenario
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MentorScenario`
        """
        model = MentorScenario()
        if include_optional:
            return MentorScenario(
                display = '',
                name = '',
                prompts = [
                    iblai.models.mentor_scenario_prompt.MentorScenarioPrompt(
                        summary = '', 
                        content = '', 
                        icon = '', )
                    ]
            )
        else:
            return MentorScenario(
                name = '',
                prompts = [
                    iblai.models.mentor_scenario_prompt.MentorScenarioPrompt(
                        summary = '', 
                        content = '', 
                        icon = '', )
                    ],
        )
        """

    def testMentorScenario(self):
        """Test MentorScenario"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
