# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.202.1-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.update_xblock import UpdateXblock

class TestUpdateXblock(unittest.TestCase):
    """UpdateXblock unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateXblock:
        """Test UpdateXblock
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateXblock`
        """
        model = UpdateXblock()
        if include_optional:
            return UpdateXblock(
                xblock_id = '',
                display_name = '',
                content = ''
            )
        else:
            return UpdateXblock(
                xblock_id = '',
        )
        """

    def testUpdateXblock(self):
        """Test UpdateXblock"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
