# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.89.4-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.llm_credential_schema import LLMCredentialSchema

class TestLLMCredentialSchema(unittest.TestCase):
    """LLMCredentialSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LLMCredentialSchema:
        """Test LLMCredentialSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LLMCredentialSchema`
        """
        model = LLMCredentialSchema()
        if include_optional:
            return LLMCredentialSchema(
                name = '',
                var_schema = None,
                service_info = iblai.models.external_service_info.ExternalServiceInfo(
                    id = 56, 
                    name = '', 
                    display_name = '', 
                    logo = '', )
            )
        else:
            return LLMCredentialSchema(
                name = '',
                service_info = iblai.models.external_service_info.ExternalServiceInfo(
                    id = 56, 
                    name = '', 
                    display_name = '', 
                    logo = '', ),
        )
        """

    def testLLMCredentialSchema(self):
        """Test LLMCredentialSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
