# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.54.3-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.bulk_program_invitation_response import BulkProgramInvitationResponse

class TestBulkProgramInvitationResponse(unittest.TestCase):
    """BulkProgramInvitationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkProgramInvitationResponse:
        """Test BulkProgramInvitationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkProgramInvitationResponse`
        """
        model = BulkProgramInvitationResponse()
        if include_optional:
            return BulkProgramInvitationResponse(
                successes = 56,
                error_codes = [
                    ''
                    ]
            )
        else:
            return BulkProgramInvitationResponse(
                successes = 56,
                error_codes = [
                    ''
                    ],
        )
        """

    def testBulkProgramInvitationResponse(self):
        """Test BulkProgramInvitationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
