# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.89.4-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.user_memory import UserMemory

class TestUserMemory(unittest.TestCase):
    """UserMemory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserMemory:
        """Test UserMemory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserMemory`
        """
        model = UserMemory()
        if include_optional:
            return UserMemory(
                mode = '',
                name = '',
                email = '',
                unique_id = '',
                username = '',
                platform = '',
                mentor = '',
                session_id = '',
                catalog_item_type = '',
                catalog_item_id = '',
                entries = [
                    iblai.models.user_memory_entry.UserMemoryEntry(
                        unique_id = '', 
                        key = '', 
                        value = '', 
                        inserted_at = '', 
                        updated_at = '', 
                        expires_at = '', 
                        category = '', )
                    ],
                inserted_at = '',
                updated_at = '',
                is_auto_generated = True,
                category = ''
            )
        else:
            return UserMemory(
                mode = '',
                email = '',
                username = '',
                platform = '',
                mentor = '',
                session_id = '',
                catalog_item_type = '',
                catalog_item_id = '',
                entries = [
                    iblai.models.user_memory_entry.UserMemoryEntry(
                        unique_id = '', 
                        key = '', 
                        value = '', 
                        inserted_at = '', 
                        updated_at = '', 
                        expires_at = '', 
                        category = '', )
                    ],
                inserted_at = '',
                updated_at = '',
        )
        """

    def testUserMemory(self):
        """Test UserMemory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
