# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.54.3-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.component_block_type_enum import ComponentBlockTypeEnum

class TestComponentBlockTypeEnum(unittest.TestCase):
    """ComponentBlockTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComponentBlockTypeEnum(self):
        """Test ComponentBlockTypeEnum"""
        # inst = ComponentBlockTypeEnum()

if __name__ == '__main__':
    unittest.main()
