# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 2.4.1-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.perlearner_grade_summary_data import PerlearnerGradeSummaryData

class TestPerlearnerGradeSummaryData(unittest.TestCase):
    """PerlearnerGradeSummaryData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PerlearnerGradeSummaryData:
        """Test PerlearnerGradeSummaryData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PerlearnerGradeSummaryData`
        """
        model = PerlearnerGradeSummaryData()
        if include_optional:
            return PerlearnerGradeSummaryData(
                assignment_type = '',
                weight = 1.337,
                weighted_grade = 1.337,
                average_section_grade = 1.337
            )
        else:
            return PerlearnerGradeSummaryData(
                assignment_type = '',
                weight = 1.337,
                weighted_grade = 1.337,
                average_section_grade = 1.337,
        )
        """

    def testPerlearnerGradeSummaryData(self):
        """Test PerlearnerGradeSummaryData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
