# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.54.3-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.api.roles_api import RolesApi


class TestRolesApi(unittest.TestCase):
    """RolesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RolesApi()

    def tearDown(self) -> None:
        pass

    def test_roles_platform_orgs_roles_users_desired_roles_retrieve(self) -> None:
        """Test case for roles_platform_orgs_roles_users_desired_roles_retrieve

        """
        pass

    def test_roles_platform_orgs_roles_users_reported_roles_retrieve(self) -> None:
        """Test case for roles_platform_orgs_roles_users_reported_roles_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
