# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.89.4-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.base_finance_response import BaseFinanceResponse

class TestBaseFinanceResponse(unittest.TestCase):
    """BaseFinanceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseFinanceResponse:
        """Test BaseFinanceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseFinanceResponse`
        """
        model = BaseFinanceResponse()
        if include_optional:
            return BaseFinanceResponse(
                metric = '',
                filters = iblai.models.finance_filters.FinanceFilters(
                    start_date = '', 
                    end_date = '', 
                    granularity = '', 
                    comparison_days = 56, 
                    platform_key = '', 
                    mentor_unique_id = '', 
                    username = '', 
                    provider = '', 
                    llm_model = '', 
                    all_time = True, ),
                value = '-807288800152802',
                percentage_change = 1.337,
                overtime = [
                    iblai.models.overtime_data.OvertimeData(
                        date = '', 
                        value = '-807288800152802', )
                    ],
                period_info = iblai.models.period_info.PeriodInfo(
                    start_date = '', 
                    end_date = '', 
                    period_days = 56, 
                    range_type = '', ),
                comparison_info = iblai.models.comparison_info.ComparisonInfo(
                    previous_period_count = 56, 
                    previous_period_value = '-807288800152802', 
                    comparison_start = '', 
                    comparison_end = '', 
                    comparison_days = 56, 
                    recent_period_value = '-807288800152802', )
            )
        else:
            return BaseFinanceResponse(
                metric = '',
                filters = iblai.models.finance_filters.FinanceFilters(
                    start_date = '', 
                    end_date = '', 
                    granularity = '', 
                    comparison_days = 56, 
                    platform_key = '', 
                    mentor_unique_id = '', 
                    username = '', 
                    provider = '', 
                    llm_model = '', 
                    all_time = True, ),
                value = '-807288800152802',
                percentage_change = 1.337,
                overtime = [
                    iblai.models.overtime_data.OvertimeData(
                        date = '', 
                        value = '-807288800152802', )
                    ],
                period_info = iblai.models.period_info.PeriodInfo(
                    start_date = '', 
                    end_date = '', 
                    period_days = 56, 
                    range_type = '', ),
                comparison_info = iblai.models.comparison_info.ComparisonInfo(
                    previous_period_count = 56, 
                    previous_period_value = '-807288800152802', 
                    comparison_start = '', 
                    comparison_end = '', 
                    comparison_days = 56, 
                    recent_period_value = '-807288800152802', ),
        )
        """

    def testBaseFinanceResponse(self):
        """Test BaseFinanceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
