# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.48.8-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.mentor_settings import MentorSettings

class TestMentorSettings(unittest.TestCase):
    """MentorSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MentorSettings:
        """Test MentorSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MentorSettings`
        """
        model = MentorSettings()
        if include_optional:
            return MentorSettings(
                id = 56,
                display_name = '',
                profile_image = '',
                initial_message = '',
                suggested_message = '',
                theme = 'dark',
                user_message_color = '',
                mentor_bubble_color = '',
                align_mentor_bubble = 'left',
                mentor = '',
                mentor_slug = '',
                mentor_unique_id = '',
                metadata = None,
                mentor_visibility = 'viewable_by_tenant_admins',
                enable_image_generation = True,
                enable_web_browsing = True,
                enable_code_interpreter = True,
                custom_css = '',
                allow_anonymous = True,
                mentor_description = '',
                suggested_prompts = None,
                proactive_response = '',
                greeting_method = '',
                mentor_tools = None,
                can_use_tools = True,
                llm_name = '',
                proactive_prompt = '',
                disclaimer = '',
                placeholder_prompt = '',
                enable_email_chat = True,
                enable_spaced_repetition = True,
                enable_instruction_mode = True,
                enable_socratic_mode = True,
                is_guided_mentor = True,
                enable_guided_prompts = True,
                enable_moderation = True,
                enable_multi_query_rag = True,
                enable_post_processing_system = True,
                enable_safety_system = True,
                forkable = True,
                forkable_with_training_data = True,
                mentor_name = '',
                categories = [
                    iblai.models.mentor_category.MentorCategory(
                        id = 56, 
                        name = '', 
                        description = '', 
                        category_group = 56, 
                        audience = iblai.models.mentor_audience.MentorAudience(
                            id = 56, 
                            name = '', 
                            description = '', ), 
                        audiences = [
                            iblai.models.mentor_audience.MentorAudience(
                                id = 56, 
                                name = '', 
                                description = '', )
                            ], )
                    ],
                types = [
                    iblai.models.mentor_type.MentorType(
                        id = 56, 
                        name = '', 
                        description = '', )
                    ],
                subjects = [
                    iblai.models.subject.Subject(
                        id = 56, 
                        name = '', 
                        description = '', )
                    ],
                recently_accessed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                platform_key = '',
                system_prompt = '',
                llm_provider = '',
                llm_temperature = 1.337,
                safety_system_prompt = '',
                safety_response = '',
                moderation_system_prompt = '',
                post_processing_prompt = '',
                moderation_response = '',
                mcp_servers = [
                    iblai.models.mcp_server.MCPServer(
                        id = 56, 
                        platform = 56, 
                        name = '', 
                        url = '', 
                        transport = 'sse', 
                        headers = null, 
                        platform_key = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                department = '',
                disable_chathistory = '',
                call_configuration = iblai.models.call_configuration.CallConfiguration(
                    id = 56, 
                    mentor = 56, 
                    mode = 'realtime', 
                    tts_provider = 'openai', 
                    stt_provider = 'openai', 
                    llm_provider = 'openai', 
                    use_function_calling_for_rag = True, 
                    google_voice = iblai.models.voice.Voice(
                        id = 56, 
                        name = '', 
                        provider = 'openai', 
                        language = '', 
                        description = '', 
                        audio_url = '', ), 
                    openai_voice = iblai.models.voice.Voice(
                        id = 56, 
                        name = '', 
                        provider = 'openai', 
                        language = '', 
                        description = '', 
                        audio_url = '', ), 
                    openai_voice_id = 56, 
                    google_voice_id = 56, 
                    enable_video = True, 
                    platform_key = '', ),
                guided_prompt_instructions = '',
                seo_tags = None,
                marketing_conversations = None,
                template_mentor = None,
                google_voice = '',
                openai_voice = '',
                enable_openai_assistant = True,
                enable_total_grounding = True,
                enable_suggested_prompts = True,
                is_deleted = True
            )
        else:
            return MentorSettings(
                id = 56,
                mentor = '',
                mentor_slug = '',
                mentor_unique_id = '',
                metadata = None,
                allow_anonymous = True,
                mentor_description = '',
                suggested_prompts = None,
                proactive_response = '',
                greeting_method = '',
                mentor_tools = None,
                can_use_tools = True,
                llm_name = '',
                proactive_prompt = '',
                disclaimer = '',
                placeholder_prompt = '',
                enable_email_chat = True,
                enable_spaced_repetition = True,
                enable_instruction_mode = True,
                enable_socratic_mode = True,
                is_guided_mentor = True,
                enable_guided_prompts = True,
                enable_moderation = True,
                enable_multi_query_rag = True,
                enable_post_processing_system = True,
                enable_safety_system = True,
                forkable = True,
                forkable_with_training_data = True,
                mentor_name = '',
                categories = [
                    iblai.models.mentor_category.MentorCategory(
                        id = 56, 
                        name = '', 
                        description = '', 
                        category_group = 56, 
                        audience = iblai.models.mentor_audience.MentorAudience(
                            id = 56, 
                            name = '', 
                            description = '', ), 
                        audiences = [
                            iblai.models.mentor_audience.MentorAudience(
                                id = 56, 
                                name = '', 
                                description = '', )
                            ], )
                    ],
                types = [
                    iblai.models.mentor_type.MentorType(
                        id = 56, 
                        name = '', 
                        description = '', )
                    ],
                subjects = [
                    iblai.models.subject.Subject(
                        id = 56, 
                        name = '', 
                        description = '', )
                    ],
                recently_accessed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                platform_key = '',
                system_prompt = '',
                llm_provider = '',
                llm_temperature = 1.337,
                safety_system_prompt = '',
                safety_response = '',
                moderation_system_prompt = '',
                post_processing_prompt = '',
                moderation_response = '',
                mcp_servers = [
                    iblai.models.mcp_server.MCPServer(
                        id = 56, 
                        platform = 56, 
                        name = '', 
                        url = '', 
                        transport = 'sse', 
                        headers = null, 
                        platform_key = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                department = '',
                disable_chathistory = '',
                call_configuration = iblai.models.call_configuration.CallConfiguration(
                    id = 56, 
                    mentor = 56, 
                    mode = 'realtime', 
                    tts_provider = 'openai', 
                    stt_provider = 'openai', 
                    llm_provider = 'openai', 
                    use_function_calling_for_rag = True, 
                    google_voice = iblai.models.voice.Voice(
                        id = 56, 
                        name = '', 
                        provider = 'openai', 
                        language = '', 
                        description = '', 
                        audio_url = '', ), 
                    openai_voice = iblai.models.voice.Voice(
                        id = 56, 
                        name = '', 
                        provider = 'openai', 
                        language = '', 
                        description = '', 
                        audio_url = '', ), 
                    openai_voice_id = 56, 
                    google_voice_id = 56, 
                    enable_video = True, 
                    platform_key = '', ),
                guided_prompt_instructions = '',
                seo_tags = None,
                marketing_conversations = None,
                template_mentor = None,
                google_voice = '',
                openai_voice = '',
                enable_openai_assistant = True,
                enable_total_grounding = True,
                enable_suggested_prompts = True,
                is_deleted = True,
        )
        """

    def testMentorSettings(self):
        """Test MentorSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
