# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 2.4.1-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.course_completion_summary_data_overtime import CourseCompletionSummaryDataOvertime

class TestCourseCompletionSummaryDataOvertime(unittest.TestCase):
    """CourseCompletionSummaryDataOvertime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CourseCompletionSummaryDataOvertime:
        """Test CourseCompletionSummaryDataOvertime
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CourseCompletionSummaryDataOvertime`
        """
        model = CourseCompletionSummaryDataOvertime()
        if include_optional:
            return CourseCompletionSummaryDataOvertime(
                overtime = {
                    'key' : null
                    },
                total_user_count = 56,
                completed_count = 56,
                completed_percent = 1.337
            )
        else:
            return CourseCompletionSummaryDataOvertime(
                total_user_count = 56,
                completed_count = 56,
                completed_percent = 1.337,
        )
        """

    def testCourseCompletionSummaryDataOvertime(self):
        """Test CourseCompletionSummaryDataOvertime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
