# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 2.4.1-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.previous_agent_status_enum import PreviousAgentStatusEnum

class TestPreviousAgentStatusEnum(unittest.TestCase):
    """PreviousAgentStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPreviousAgentStatusEnum(self):
        """Test PreviousAgentStatusEnum"""
        # inst = PreviousAgentStatusEnum()

if __name__ == '__main__':
    unittest.main()
