# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 2.3.36-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.net_revenue_over_time import NetRevenueOverTime

class TestNetRevenueOverTime(unittest.TestCase):
    """NetRevenueOverTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NetRevenueOverTime:
        """Test NetRevenueOverTime
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NetRevenueOverTime`
        """
        model = NetRevenueOverTime()
        if include_optional:
            return NetRevenueOverTime(
                data = [
                    iblai.models.float_over_time.FloatOverTime(
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        total = 1.337, )
                    ],
                total = 1.337
            )
        else:
            return NetRevenueOverTime(
        )
        """

    def testNetRevenueOverTime(self):
        """Test NetRevenueOverTime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
