# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.89.4-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.mentor_from_template_with_setting_request import MentorFromTemplateWithSettingRequest

class TestMentorFromTemplateWithSettingRequest(unittest.TestCase):
    """MentorFromTemplateWithSettingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MentorFromTemplateWithSettingRequest:
        """Test MentorFromTemplateWithSettingRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MentorFromTemplateWithSettingRequest`
        """
        model = MentorFromTemplateWithSettingRequest()
        if include_optional:
            return MentorFromTemplateWithSettingRequest(
                template_name = '',
                display_name = '',
                description = '',
                profile_image = '',
                initial_message = '',
                suggested_message = '',
                new_mentor_name = '',
                theme = '',
                user_message_color = '',
                mentor_bubble_color = '',
                align_mentor_bubble = '',
                system_prompt = '',
                llm_provider = '',
                llm_name = '',
                mentor_visibility = '',
                enable_image_generation = True,
                enable_web_browsing = True,
                enable_code_interpreter = True,
                metadata = None,
                custom_css = '',
                uploaded_profile_image = '',
                proactive_response = '',
                greeting_method = 'proactive_prompt',
                forkable = True,
                forkable_with_training_data = True,
                categories = [
                    56
                    ],
                types = [
                    56
                    ],
                subjects = [
                    56
                    ],
                tool_slugs = [
                    ''
                    ],
                llm_temperature = 0.0,
                seo_tags = None,
                marketing_conversations = None,
                proactive_prompt = '',
                disclaimer = '',
                enable_disclaimer = True,
                embed_is_context_aware = True,
                embed_open_by_default = True,
                embed_show_attachment = True,
                embed_show_voice_call = True,
                embed_show_voice_record = True,
                placeholder_prompt = '',
                moderation_system_prompt = '',
                post_processing_prompt = '',
                moderation_response = '',
                enable_moderation = True,
                enable_multi_query_rag = True,
                enable_post_processing_system = True,
                enable_openai_assistant = True,
                enable_total_grounding = True,
                google_voice = 56,
                openai_voice = 56,
                enable_suggested_prompts = True,
                enable_guided_prompts = True,
                mcp_servers = [
                    56
                    ],
                guided_prompt_instructions = '',
                is_featured = True
            )
        else:
            return MentorFromTemplateWithSettingRequest(
                template_name = '',
                new_mentor_name = '',
        )
        """

    def testMentorFromTemplateWithSettingRequest(self):
        """Test MentorFromTemplateWithSettingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
