# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.6.0-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.skill_info import SkillInfo

class TestSkillInfo(unittest.TestCase):
    """SkillInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SkillInfo:
        """Test SkillInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SkillInfo`
        """
        model = SkillInfo()
        if include_optional:
            return SkillInfo(
                id = 56,
                name = '',
                course_count = 56,
                user_count = 56,
                total_points = 56,
                average_points = 1.337
            )
        else:
            return SkillInfo(
                id = 56,
                course_count = 56,
                user_count = 56,
                total_points = 56,
                average_points = 1.337,
        )
        """

    def testSkillInfo(self):
        """Test SkillInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
