# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.54.3-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.user_trend_by_period import UserTrendByPeriod

class TestUserTrendByPeriod(unittest.TestCase):
    """UserTrendByPeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserTrendByPeriod:
        """Test UserTrendByPeriod
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserTrendByPeriod`
        """
        model = UserTrendByPeriod()
        if include_optional:
            return UserTrendByPeriod(
                periods = [
                    datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
                    ],
                new_users = [
                    56
                    ],
                veteran_users = [
                    56
                    ]
            )
        else:
            return UserTrendByPeriod(
                periods = [
                    datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
                    ],
                new_users = [
                    56
                    ],
                veteran_users = [
                    56
                    ],
        )
        """

    def testUserTrendByPeriod(self):
        """Test UserTrendByPeriod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
