# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.54.3-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.heygen_marketing_video_list import HeygenMarketingVideoList

class TestHeygenMarketingVideoList(unittest.TestCase):
    """HeygenMarketingVideoList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HeygenMarketingVideoList:
        """Test HeygenMarketingVideoList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HeygenMarketingVideoList`
        """
        model = HeygenMarketingVideoList()
        if include_optional:
            return HeygenMarketingVideoList(
                name = '',
                data = None,
                pk = 56,
                generation_status = ''
            )
        else:
            return HeygenMarketingVideoList(
                pk = 56,
                generation_status = '',
        )
        """

    def testHeygenMarketingVideoList(self):
        """Test HeygenMarketingVideoList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
