# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.54.3-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.email_prompt_detail import EmailPromptDetail

class TestEmailPromptDetail(unittest.TestCase):
    """EmailPromptDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmailPromptDetail:
        """Test EmailPromptDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmailPromptDetail`
        """
        model = EmailPromptDetail()
        if include_optional:
            return EmailPromptDetail(
                id = 56,
                inserted_at = '',
                sender_email = '',
                sender_name = '',
                subject = '',
                content = '',
                mentor_name = '',
                mentor_email = '',
                is_processed = True,
                mentor_response = '',
                send_status = ''
            )
        else:
            return EmailPromptDetail(
                id = 56,
                inserted_at = '',
                sender_email = '',
                content = '',
                mentor_email = '',
        )
        """

    def testEmailPromptDetail(self):
        """Test EmailPromptDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
