# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.54.3-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.course_group_suggestion_create import CourseGroupSuggestionCreate

class TestCourseGroupSuggestionCreate(unittest.TestCase):
    """CourseGroupSuggestionCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CourseGroupSuggestionCreate:
        """Test CourseGroupSuggestionCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CourseGroupSuggestionCreate`
        """
        model = CourseGroupSuggestionCreate()
        if include_optional:
            return CourseGroupSuggestionCreate(
                platform_key = '',
                course_id = '',
                group_id = 56,
                accepted = True,
                visible = True,
                metadata = {
                    'key' : null
                    },
                suggested_by = '',
                direct = True,
                department_mode = True
            )
        else:
            return CourseGroupSuggestionCreate(
                platform_key = '',
                course_id = '',
                group_id = 56,
        )
        """

    def testCourseGroupSuggestionCreate(self):
        """Test CourseGroupSuggestionCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
