# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.204.2-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iblai.models.starter_prompts_b04_enum import StarterPromptsB04Enum

class TestStarterPromptsB04Enum(unittest.TestCase):
    """StarterPromptsB04Enum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStarterPromptsB04Enum(self):
        """Test StarterPromptsB04Enum"""
        # inst = StarterPromptsB04Enum()

if __name__ == '__main__':
    unittest.main()
