# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.89.3-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AuthTypeEnum(str, Enum):
    """
    * `none` - None * `token` - Token * `oauth2` - Oauth2
    """

    """
    allowed enum values
    """
    NONE = 'none'
    TOKEN = 'token'
    OAUTH2 = 'oauth2'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AuthTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


