# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 4.204.2-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class PatchedGoogleAgentDetail(BaseModel):
    """
    PatchedGoogleAgentDetail
    """ # noqa: E501
    id: Optional[StrictInt] = None
    sub_agents: Optional[StrictStr] = None
    platform: Optional[StrictStr] = None
    unique_id: Optional[UUID] = None
    model: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    instruction: Optional[StrictStr] = None
    output_key: Optional[StrictStr] = None
    inserted_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    created_by: Optional[StrictInt] = Field(default=None, description="edX user ID")
    __properties: ClassVar[List[str]] = ["id", "sub_agents", "platform", "unique_id", "model", "name", "description", "instruction", "output_key", "inserted_at", "updated_at", "created_by"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchedGoogleAgentDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "sub_agents",
            "platform",
            "inserted_at",
            "updated_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if output_key (nullable) is None
        # and model_fields_set contains the field
        if self.output_key is None and "output_key" in self.model_fields_set:
            _dict['output_key'] = None

        # set to None if created_by (nullable) is None
        # and model_fields_set contains the field
        if self.created_by is None and "created_by" in self.model_fields_set:
            _dict['created_by'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchedGoogleAgentDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "sub_agents": obj.get("sub_agents"),
            "platform": obj.get("platform"),
            "unique_id": obj.get("unique_id"),
            "model": obj.get("model"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "instruction": obj.get("instruction"),
            "output_key": obj.get("output_key"),
            "inserted_at": obj.get("inserted_at"),
            "updated_at": obj.get("updated_at"),
            "created_by": obj.get("created_by")
        })
        return _obj


