# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.66.0-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProgramTypeEnum(str, Enum):
    """
    * `bachelors` - Bachelor's Degree * `masters` - Master's Degree * `phd` - PhD * `diploma` - Diploma * `certificate` - Certificate * `ungraded` - Ungraded * `other` - Other
    """

    """
    allowed enum values
    """
    BACHELORS = 'bachelors'
    MASTERS = 'masters'
    PHD = 'phd'
    DIPLOMA = 'diploma'
    CERTIFICATE = 'certificate'
    UNGRADED = 'ungraded'
    OTHER = 'other'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProgramTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


