# coding: utf-8

"""
    ibl-data-manager

    API for iblai

    The version of the OpenAPI document: 3.66.0-ai-plus
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from iblai.models.user_metric import UserMetric
from typing import Optional, Set
from typing_extensions import Self

class UserMetricsResponse(BaseModel):
    """
    UserMetricsResponse
    """ # noqa: E501
    registered_users: UserMetric
    new_users: UserMetric
    unique_users: UserMetric
    veteran_users: UserMetric
    __properties: ClassVar[List[str]] = ["registered_users", "new_users", "unique_users", "veteran_users"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserMetricsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of registered_users
        if self.registered_users:
            _dict['registered_users'] = self.registered_users.to_dict()
        # override the default output from pydantic by calling `to_dict()` of new_users
        if self.new_users:
            _dict['new_users'] = self.new_users.to_dict()
        # override the default output from pydantic by calling `to_dict()` of unique_users
        if self.unique_users:
            _dict['unique_users'] = self.unique_users.to_dict()
        # override the default output from pydantic by calling `to_dict()` of veteran_users
        if self.veteran_users:
            _dict['veteran_users'] = self.veteran_users.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserMetricsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "registered_users": UserMetric.from_dict(obj["registered_users"]) if obj.get("registered_users") is not None else None,
            "new_users": UserMetric.from_dict(obj["new_users"]) if obj.get("new_users") is not None else None,
            "unique_users": UserMetric.from_dict(obj["unique_users"]) if obj.get("unique_users") is not None else None,
            "veteran_users": UserMetric.from_dict(obj["veteran_users"]) if obj.get("veteran_users") is not None else None
        })
        return _obj


